"""
E2E tests for Account API endpoints.

Tests the full HTTP stack:
  POST /api/v1/accounts/ → EventStore writes event + outbox → 201
  GET  /api/v1/accounts/{id} → reads projection (fast) OR replays events (slow)

No Kafka running = projection table always empty for new accounts.
Every GET therefore proves the event replay fallback works.
"""
import pytest
from uuid import UUID
from decimal import Decimal
pytestmark = pytest.mark.asyncio

class TestCreateAccount:
    """POST /api/v1/accounts/ — the Command side of CQRS."""
    async def test_return_201_with_account_id(self, api_client):
        """
        When a new account is created, the API must return 201 + account_id.
        The account_id is generated by the server and returned in the response.
        """
        response = await api_client.post(
            "/api/v1/accounts/",
            json={
                "name": "Test Account",
                "account_type": "CHECKING",
                "currency": "USD",
                "initial_balance": "5000.00",
            },
        )

        assert response.status_code == 201
        body = response.json()
        assert "account_id" in body
        assert body["status"] == "created"
        UUID(body["account_id"])  # valid UUID format
    async def test_event_written_to_event_store(self, api_client, db_pool):
        """
        After creating an account, the events table must have a new row.
        This proves the API endpoint correctly calls EventStore.append_events().
        """
        # Create account via API
        response = await api_client.post(
            "/api/v1/accounts/",
            json={
                "name": "Test Account",
                "account_type": "CHECKING",
                "currency": "NOK",
                "initial_balance": "5000.00",
            },
        )
        account_id = UUID(response.json()["account_id"])
        # Query events table directly to confirm event was written
        async with db_pool.acquire() as conn:
            row = await conn.fetchrow(
                "SELECT * FROM events WHERE aggregate_id = $1 ORDER BY created_at DESC LIMIT 1",
                account_id,
            )

        assert row is not None
        assert row["event_type"] == "AccountCreated"
    async def test_outbox_row_created_for_kafka(self, api_client, db_pool):
        # Proves the outbox pattern: EventStore wrote BOTH events + outbox atomically
        # published_at = None means OutboxRelay hasn't picked it up yet
        response = await api_client.post(
            "/api/v1/accounts/",
            json={
                "name": "Vipps Konto",
                "account_type": "CHECKING",
                "currency": "NOK",
                "initial_balance": "5000.00",
            },
        )
        account_id = UUID(response.json()["account_id"])
        async with db_pool.acquire() as conn:
            row = await conn.fetchrow(
                "SELECT event_type, published_at FROM outbox WHERE aggregate_id = $1",
                account_id,
            )

        assert row is not None
        assert row["event_type"] == "AccountCreated"
        assert row["published_at"] is None   # not yet sent to Kafka
    
    async def test_invalid_currency_returns_422(self, api_client):
        # Currency enum in Pydantic schema only allows NOK/EUR/USD
        # 422 = Unprocessable Entity (FastAPI's validation error response)
        response = await api_client.post("/api/v1/accounts/", json={
            "name": "Test",
            "currency": "INVALID",
            "account_type": "CHECKING",
            "initial_balance": "1000.00",
        })

        assert response.status_code == 422
class TestGetAccount:
    """GET /api/v1/accounts/{id} — the Query side of CQRS."""

    async def test_get_nonexistent_returns_404(self, api_client):
        # No events for this UUID → AggregateNotFoundError → route converts to 404
        response = await api_client.get(
            "/api/v1/accounts/00000000-0000-0000-0000-000000000099"
        )
        assert response.status_code == 404
    async def test_get_uses_event_replay_fallback(self, api_client, db_pool):
        """
        With no Kafka running, the projection table is always empty for new accounts.
        Every GET therefore proves the event replay fallback works.
        The most important CQRS test:
        POST creates an AccountCreated event → GET replays that event.
        No projection row exists (no consumer ran) → slow path is forced.
        Proves the system stays correct during the eventual consistency window.
        
        """
        # Create account via API
        create_response = await api_client.post("/api/v1/accounts/", json={
                "name": "Replay Test",
                "account_type": "SAVINGS",
                "currency": "NOK",
                "initial_balance": "3000.00",
            },
        )
        assert create_response.json()["account_id"]
        account_id = create_response.json()["account_id"]
        # GET the account — must succeed even with empty projection table
        get_response = await api_client.get(f"/api/v1/accounts/{account_id}")
        assert get_response.status_code == 200
        body = get_response.json()
        assert Decimal(body["balance"]) == Decimal("3000.00")
        assert body["name"] == "Replay Test"
